// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOED5evDmlf9usWxb6-4EZfe0wO0PQxs4',
    appId: '1:657048619745:web:8b3e000329c1dd576205a0',
    messagingSenderId: '657048619745',
    projectId: 'hadaer-blady',
    authDomain: 'hadaer-blady.firebaseapp.com',
    storageBucket: 'hadaer-blady.firebasestorage.app',
    measurementId: 'G-VDM5V0F6LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCylDPxAlwNMY3WC2cI6RmIH-a7vqCopo0',
    appId: '1:657048619745:android:ca6c2be33ecf80bd6205a0',
    messagingSenderId: '657048619745',
    projectId: 'hadaer-blady',
    storageBucket: 'hadaer-blady.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgZDcLtjGIQY1NI8NfNXRu-6PGiMwA10',
    appId: '1:657048619745:ios:b4cb5db2f584ff016205a0',
    messagingSenderId: '657048619745',
    projectId: 'hadaer-blady',
    storageBucket: 'hadaer-blady.firebasestorage.app',
    iosBundleId: 'com.hadaer_blady.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgZDcLtjGIQY1NI8NfNXRu-6PGiMwA10',
    appId: '1:657048619745:ios:b4cb5db2f584ff016205a0',
    messagingSenderId: '657048619745',
    projectId: 'hadaer-blady',
    storageBucket: 'hadaer-blady.firebasestorage.app',
    iosBundleId: 'com.hadaer_blady.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOED5evDmlf9usWxb6-4EZfe0wO0PQxs4',
    appId: '1:657048619745:web:17b3595f226ec51f6205a0',
    messagingSenderId: '657048619745',
    projectId: 'hadaer-blady',
    authDomain: 'hadaer-blady.firebaseapp.com',
    storageBucket: 'hadaer-blady.firebasestorage.app',
    measurementId: 'G-0L80RDHHRB',
  );
}